
import { ContextProvider } from "@/app/context";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          <div className="h-screen flex justify-center items-center">
            <div className="rounded-lg bg-white h-[80vh] w-[400px]">
              <div className=" mt-2 flex justify-center">
                <h1 className="p-0 m-0 text-blue-600">
                  Brand<span className="font-[100]">fy</span>
                </h1>
              </div>
              <div className="h-[100%] p-4">{children}</div>
            </div>
          </div>
        </body>
      </ContextProvider>
    </html>
  );
}
